# Generated by Django 5.2.5 on 2025-08-30 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='MainImage/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('redis', 'redis'), ('celery', 'celery'), ('celery_beat', 'celery_beat'), ('django-allauth', 'django-allauth'), ('django-environ', 'django-environ'), ('django-jazzmin', 'django-jazzmin'), ('django-modeltranslation', 'django-modeltranslation'), ('django-phonenumber-field', 'django-phonenumber-field'), ('DjangoRestFramework', 'DjangoRestFramework'), ('phonenumbers', 'phonenumbers'), ('postgresql', 'postgresql'), ('stripe', 'stripe'), ('whitenoise', 'whitenoise'), ('Bucket', 'Bucket'), ('Docker', 'Docker')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='WorkImages/')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='core.work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='WorkInfo',
            field=models.ManyToManyField(to='core.workinfo'),
        ),
    ]
